//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeekProProgress
{
    using System;
    using System.Collections.Generic;
    
    public partial class Journal
    {
        public int id { get; set; }
        public int id_student { get; set; }
        public int id_user { get; set; }
        public string title { get; set; }
        public int numGrade { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual Students Students { get; set; }
        public virtual Users Users { get; set; }
    }
}
